apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: llm-d-lab
  annotations:
    argocd.argoproj.io/cascade: "foreground"
spec:
  destination:
    name: ''
    namespace: 'openshift-gitops'
    server: 'https://kubernetes.default.svc'
  source:
    path: envs/baremetal-lab
    repoURL: https://github.com/bbenshab/llm-d-lab.git
    targetRevision: master
    kustomize:
       patches:
         # Patch to change repoURL for all Applications with the llm-d-lab label
         - target:
             kind: Application
             group: argoproj.io
             version: v1alpha1
             labelSelector: app.kubernetes.io/managed-by=llm-d-lab
           patch: |-
             - op: replace
               path: /spec/source/repoURL
               value: https://github.com/bbenshab/llm-d-lab.git
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 10m0s
        factor: 2
