apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-preparation
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: llm-d-lab
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/00-node-preparation
    repoURL: https://github.com/bbenshab/llm-d-lab.git
    targetRevision: master
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
