apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nvidia-mofed-ready
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: llm-d-lab
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: nvidia-network-operator
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/29-nvidia-mofed-ready
    repoURL: https://github.com/bbenshab/llm-d-lab.git
    targetRevision: master
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 8
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
