apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: multiarch-tuning-operator
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: llm-d-lab
spec:
  destination:
    name: ''
    namespace: openshift-multiarch-tuning-operator
    server: 'https://kubernetes.default.svc'
  source:
    path: manifests/25-multiarch-tuning-operator
    repoURL: https://github.com/aleskandro/llm-d-lab.git
    targetRevision: master
  sources: []
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: false
    syncOptions:
      - ServerSideApply=true
    retry:
      limit: 8
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
